Awards section
Jullija/oops pull request #109
Opened 2024-10-01 13:44 UTC by AnCichocka

2024-10-01 18:39 UTC, Szyntos requested changes
Looks nice, but shouldn't the hover be applied also on the bonuses in the student's table?

![image](https://github.com/user-attachments/assets/6e43729b-9791-4934-bb48-40ef91361cff)

here?

2024-10-01 18:39 UTC, Szyntos commented on frontend/src/components/StudentProfile/cards/BonusesCard.tsx
> +import { Bonus } from "../../../hooks/StudentProfile/useBonusesCardData";
Theoretically this should be an Award

In backend Award is the entity that gives the points (LEKARSTWO)
and Bonus is the result of that award, i.e. a triple (chestHistory, award, points)

IDK if it's worth the trouble tho

2024-10-01 18:39 UTC, Szyntos commented on frontend/src/components/StudentProfile/table/cellContent/PointsCellContent.tsx
> +      ? undefined
Isn't the inverse more readable?

```js
points.points.partialBonusType.length != 0
      ? points.points.partialBonusType.reduce(
          (total, bonus) => total + (bonus?.partialValue ?? 0)
          , 0)
        ? undefined
```

truly, idk

2024-10-01 18:39 UTC, Szyntos commented on frontend/src/components/StudentProfile/table/cellContent/PointsCellContent.tsx
> +      return undefined;
Label in points tells you about the origin of the points, i.e. "Awarded for Lekarstwo"

2024-10-01 18:39 UTC, Szyntos commented on frontend/src/hooks/StudentProfile/useBonusesCardData.tsx
> +          imgId: bonus.award.imageFileId ?? undefined,
There is image/bonus/sample on back

i could make samples as a permanent data on the db and we could use them here

2024-10-01 18:39 UTC, Szyntos commented on frontend/src/hooks/StudentProfile/useBonusesCardData.tsx
> +          imgId: bonus.award.imageFileId ?? undefined,
But this is a separate ticket

2024-10-01 20:35 UTC, AnCichocka commented on frontend/src/components/StudentProfile/cards/BonusesCard.tsx
> +import { Bonus } from "../../../hooks/StudentProfile/useBonusesCardData";
I don't think so, as long as I know what it's all about

2024-10-02 19:29 UTC, AnCichocka commented on frontend/src/hooks/StudentProfile/useBonusesCardData.tsx
> +          imgId: bonus.award.imageFileId ?? undefined,
Can you create jira ticket?

2024-10-02 19:30 UTC, AnCichocka commented on frontend/src/components/StudentProfile/table/cellContent/PointsCellContent.tsx
> +      ? undefined
tbh, no difference, I can change that

2024-10-03 06:49 UTC, Szyntos approved these changes
mlgt

2024-10-03 20:13 UTC, merged