[FE-151] [FE-152] All levels section, update progress bar
Jullija/oops pull request #112
Opened 2024-10-05 14:15 UTC by AnCichocka

https://oops2000.atlassian.net/browse/SCRUM-151
https://oops2000.atlassian.net/browse/SCRUM-152

2024-10-05 15:00 UTC, AnCichocka commented on frontend/src/hooks/StudentProfile/useStudentProfileData/useAnimalData.tsx
> +    maximumPoints: parseInt(data.maximumPoints),
Should it be `parseInt` of `parseFloat`?

2024-10-08 20:41 UTC, AnCichocka commented on frontend/src/components/StudentProfile/cards/AnimalCard/LevelsSection.tsx
> +            <AnimalWithTooltip
TODO correct name, I missed that

2024-10-08 20:44 UTC, AnCichocka commented on frontend/src/components/bars/LevelProgressBar/LevelProgressBar.tsx
> +          upper: currLevel.maximumPoints - currLevel.minimumPoints,
@Szyntos please check if it's correct, I mean when min = 10 and max = 20 should I display interval 10-20, 11-20, 10-19 or 10-20?

2024-10-08 20:46 UTC, AnCichocka commented on frontend/src/components/images/AnimalWithTooltip.tsx
> +            from {level.minimumPoints} to {level.maximumPoints} points
@Szyntos here as well

2024-10-10 18:40 UTC, Szyntos commented on frontend/src/hooks/StudentProfile/useLevelsData.tsx
> +    variables: { editionId: editionId },
![image](https://github.com/user-attachments/assets/c3adcfd7-79de-494f-8df2-d25a0d92c6da)
userId = 15

useLevelsData queries for editionId=2, where in fact this user is in editionId=1

2024-10-10 18:42 UTC, Szyntos commented on frontend/src/hooks/StudentProfile/useStudentProfileData/useAnimalData.tsx
> +    maximumPoints: parseInt(data.maximumPoints),
This is a question whether we should allow floating point level range. On Backend we're allowing it, so i guess we should change it to float

2024-10-10 18:44 UTC, Szyntos commented on frontend/src/components/bars/LevelProgressBar/LevelProgressBar.tsx
> +          upper: currLevel.maximumPoints - currLevel.minimumPoints,
IMO the interval should be displayed as

```[10, 20), [20, 30)```

the lower bound is inclusive, the upper is exclusive

2024-10-10 18:46 UTC, Szyntos requested changes
One error with userId=15

2024-10-11 15:03 UTC, AnCichocka commented on frontend/src/components/bars/LevelProgressBar/LevelProgressBar.tsx
> +          upper: currLevel.maximumPoints - currLevel.minimumPoints,
So i should do 10-19? or leave 20 to display?

2024-10-11 19:57 UTC, AnCichocka commented on frontend/src/hooks/StudentProfile/useLevelsData.tsx
> +    variables: { editionId: editionId },
> ![image](https://private-user-images.githubusercontent.com/40152296/375503832-c3adcfd7-79de-494f-8df2-d25a0d92c6da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzY0MzMsIm5iZiI6MTcyODY3NjEzMywicGF0aCI6Ii80MDE1MjI5Ni8zNzU1MDM4MzItYzNhZGNmZDctNzlkZS00OTRmLThkZjItZDI1YTBkOTJjNmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE5NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMGJkMTc1Y2Y3N2Y4OTI2MmUxOTJhMzRmZjRkMTZhOGNjNTFhZGU0OTE4OGZkOTBhMjFjYTZkZjAyZTk2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7OZnfbdRdFAIXnyc4E8ItTqDlLbUqNRnMQW7qKys0z8) userId = 15
> 
> useLevelsData queries for editionId=2, where in fact this user is in editionId=1

maybe that's the case xd

`query Levels($editionId: bigint) {
  levels(where: { editionId: { _eq: 2 } }, orderBy: { ordinalNumber: ASC }) {
    grade
    imageFileId
    levelId
    maximumPoints
    minimumPoints
    name
    ordinalNumber
    label
    highest
    editionId
  }
}
`

2024-10-11 20:01 UTC, AnCichocka commented
> One error with userId=15

now it works 💪

2024-10-11 22:51 UTC, Szyntos requested changes

2024-10-11 22:51 UTC, Szyntos commented on frontend/src/graphql/levels.graphql
> +query Levels($editionId: bigint) {
1. It should be Int!

```graphql
query Levels($editionId: Int!) {
  levels(
    where: { editionId: { _eq: editionId } }
    orderBy: { ordinalNumber: ASC }
  ) {
    grade
    imageFileId
    levelId
    maximumPoints
    minimumPoints
    name
    ordinalNumber
    label
    highest
    editionId
  }
}
```

2. I get this error:

![image](https://github.com/user-attachments/assets/d8b1041d-0584-4c3c-92d9-37e12d354487)


```json
{
    "errors": [
        {
            "message": "expecting a value for non-nullable variable: \"editionId\"",
            "extensions": {
                "path": "$",
                "code": "validation-failed"
            }
        }
    ]
}
```

You're not sending variables somehow

2024-10-11 22:51 UTC, Szyntos commented on frontend/src/graphql/levels.graphql
> +query Levels($editionId: bigint) {
Even without the change to Int! there is the same error:

![image](https://github.com/user-attachments/assets/9e52bd7a-1085-40e2-97ff-82949308ee35)

![image](https://github.com/user-attachments/assets/d39b7bca-c59e-4dc9-b180-729df3c24b5e)

2024-10-15 16:52 UTC, AnCichocka commented on frontend/src/graphql/levels.graphql
> +query Levels($editionId: bigint) {
sus

2024-10-15 19:23 UTC, Szyntos approved these changes
WORKSSSSS

2024-10-15 19:24 UTC, merged