[TEACHER] Group list & group screen
Jullija/oops pull request #23
Opened 2024-06-25 16:31 UTC by AnCichocka

- create Groups List screen
<img width="1512" alt="image" src="https://github.com/Jullija/oops/assets/115690306/903cb0d4-a3a6-4e93-bb51-f67e4a43675c">

- create Group screen
<img width="1511" alt="image" src="https://github.com/Jullija/oops/assets/115690306/125f25d1-d46d-4d95-9076-90edd625b4d4">

- connect Groups List screen with Group List - I created ticket to connect Group Screen with Student Profile
- fetch needed information from backend

2024-06-25 16:31 UTC, AnCichocka commented on frontend/src/graphql/getGroup.graphql
> +    userGroups(orderBy: { user: { secondName: ASC, firstName: ASC } }) {
I wanted fetched list of users to be sorted by seconName and firstName, but It seems like I can sort only by one of this value. Does anyone know any other smart way?

2024-06-29 13:50 UTC, dadamczykk commented on frontend/src/graphql/getGroup.graphql
> +    userGroups(orderBy: { user: { secondName: ASC, firstName: ASC } }) {
```
query getGroup {
  groups {
    userGroups(
      orderBy: [{ user: { secondName: ASC } }, { user: { firstName: ASC } }]
    ) {
      userId
      user {
        firstName
        secondName
      }
    }
    groupName
  }
}
``` 

this syntax should do the job, It sorts userGroups objects by second name first, and than by first name.

2024-06-30 19:40 UTC, dadamczykk commented on frontend/src/graphql/getGroups.graphql
> +query getGroups($editionId: bigint!) {
Graphql has basically two types of interactions, queries and mutations. Queries are used always as equivalent of http get, mutations are responsible for delete, update, create. Thats why good convention (that I'm using) is to not include get in queries names. For example here good name woudl be ```Groups``` or ```GroupsByEdition```. The generated hook will have ```useGruopsQuery```name which is rather enough to determinate that it doesn't change anything in db, and just queries data

2024-06-30 19:40 UTC, dadamczykk commented on frontend/src/graphql/getGroup.graphql
> +}
Instead of filtering by group here, you can use ```groupByPk```. With that you can get only one group object, and than check if the editionId is alright. It would be more efficient from db perspective, becuse there will be no filtering done every time the query is used, especially if final object is either one group entry, or null

```
query Group($groupId: bigint!) {
  groupsByPk(groupsId: $groupId) {
    userGroups(orderBy: { user: { secondName: ASC, firstName: ASC } }) {
      userId
      user {
        firstName
        secondName
      }
    }
    groupName
  }
}
```

2024-06-30 20:08 UTC, AnCichocka commented on frontend/src/graphql/getGroup.graphql
> +    userGroups(orderBy: { user: { secondName: ASC, firstName: ASC } }) {
Now there is `fullName` available so I'll use it

2024-06-30 20:31 UTC, AnCichocka commented on frontend/src/hooks/Groups/useGroupsData.tsx
> +      editionId: selectedEdition?.editionId ?? "-1",
Do we want to handle it in any better way?

2024-06-30 20:31 UTC, AnCichocka commented on frontend/src/router/paths.tsx
> +// do not use outside ./router
I am wondering if we should move it to `/paths` and do not export it - I saw somewhere in code it being used outside `./router`

2024-06-30 21:14 UTC, AnCichocka commented on frontend/src/graphql/getGroup.graphql
> +}
I merge two queries to one and looks like I cannot use `groupsByPk`, because I have no availability to filter by `role`, I also resigned from adding `orderBy`, because I didn't know how to do that in hasura API. If you can have a look on `groupsByEdition` I would be grateful, maybe there is some better way to do that

2024-06-30 21:16 UTC, AnCichocka commented on frontend/.eslintcache
> +[{"/Users/cichocka/Desktop/oops/frontend/src/components/form/NumberInput.tsx":"1","/Users/cichocka/Desktop/oops/frontend/src/components/form/SelectInput.tsx":"2"},{"size":711,"mtime":1719343259837,"r
It's already in `.gitignore`. It seems like my `.eslintcache` was added before merge that's why `.gitignore` didn't catch it. I deleted it form repository and `.gitignore` seems to works just fine.

2024-06-30 22:17 UTC, dadamczykk commented on frontend/src/graphql/getGroup.graphql
> +}
If you don't have some hasura fields visible it's worth to add headers, especially ```x-hasura-role```. It makes api (the one you click to get queries) adjust tables, fields and relations that user with given role has permission to

<img width="1775" alt="image" src="https://github.com/Jullija/oops/assets/70212130/d9f660fa-d7bd-4106-8cff-6ae938a719a2">

2024-06-30 22:23 UTC, dadamczykk commented on frontend/src/graphql/groupsByEdition.graphql
> +  }
I don't really know why hasura didn't allow you to write those queries with where at appropriate place. one possible thing is that api

Basically in case of this query you can skip filtering (first where) with example above

```
query GroupsByEdition($editionId: bigint!) {
  editionByPk(editionId: $editionId) {
    groups {
      groupName
      groupsId
      userGroups(where: {user: {role: {_eq: "student"}}}) {
        user {
          userId
          fullName
          role
        }
      }
    }
  }
}
```

Another approach would query for groups and filter them by associated edition

```
query GroupsByEdition($editionId: bigint!) {
  groups(where: {editionId: {_eq: $editionId}}) {
    groupName
    groupsId
    userGroups(where: {user: {role: {_eq: "student"}}}) {
      user {
        userId
        fullName
        role
      }
    }
  }
}
```

but from the db point of view it may be less efficient, since we're adding additional ```where``` statement.

2024-06-30 22:23 UTC, dadamczykk commented on frontend/src/graphql/getGroup.graphql
> +}
I've checked again and the issue was that in case of relation ```userGroups -> user``` if you want to apply filter on users you have to apply it directly on ```userGroups```, that is because ```userGroups``` is table that just provides many-to-many relationship between users and groups, and there would be no sense to query for ```userGroups``` without querying for user. In case of query above it would look like below.

```
query getGroup($editionId: bigint!, $groupId: bigint!) {
  groups(where: {editionId: {_eq: $editionId}, groupsId: {_eq: $groupId}}) {
    userGroups(orderBy: {user: {secondName: ASC, firstName: ASC}}, where: {user: {role: {_eq: "student"}}}) {
      userId
      user {
        firstName
        secondName
      }
    }
    groupName
  }
}
```

It's clicked from hasura

2024-06-30 23:20 UTC, dadamczykk requested changes

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/Groups/Groups.tsx
> +    </div>
For now it's alright, but when we decide on designs we should probably split gropus view and students view

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/Groups/StudentSearcher/StudentCard.tsx
> +};
You could probably use ```SearchStudent``` type, maybe renaming it would do the job so it is more reusable

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/Groups/StudentSearcher/StudentSearcher.tsx
> +          .includes(searchInputValue.toLowerCase()),
It'll be good to make separate function in ```utils```. something like below. It's great to use ```trim()``` in those

```
export const isPartOfAString = (searchValue: string, str: string) =>
  str.toLowerCase().includes(searchValue.trim().toLowerCase());
```

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/Groups/StudentSearcher/StudentSearcher.tsx
> +
I'd suggest changing it so instead of function it is just an array of filtered students that is computed every time search input change. We could than utilise memorization to make performance a little better, and make sure it does't compute every re-render. It would look like this

```
  const filteredStudents = useMemo(() => {
    return students.filter((student) =>
      student.fullName?.toLowerCase().includes(searchInputValue.toLowerCase())
    );
  }, [students, searchInputValue]);
  ```

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/Groups/StudentSearcher/index.ts
> +export * from "./StudentSearcher";
I thought we're not doing [barrels](https://uglow.medium.com/burn-the-barrel-c282578f21b6)

2024-06-30 23:20 UTC, dadamczykk commented on frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx
> +  const studentId = params.id;
Could it be moved to ```useTeacherStudentData```. In there you could do the same thing with query optional arguments and skip variables, so you wouldn't have to bother with Id being undefined. Also the hook wouldn't require to have parameters passed.

2024-06-30 23:23 UTC, dadamczykk commented
Overall pretty good job! And congrats on wriging first graphql queries!

2024-07-01 19:27 UTC, AnCichocka commented on frontend/src/screens/Groups/StudentSearcher/index.ts
> +export * from "./StudentSearcher";
yeah, sorry I did it automatically - I created a ticket to delete all `index.ts` files

2024-07-01 19:35 UTC, AnCichocka commented on frontend/src/hooks/Groups/useGroupsData.tsx
> +      editionId: selectedEdition?.editionId ?? "-1",
shouldn't we then change also `usePoints` query?

2024-07-01 19:36 UTC, AnCichocka commented on frontend/src/router/paths.tsx
> +// do not use outside ./router
I created single ticket to handle that

2024-07-01 19:38 UTC, AnCichocka commented on frontend/src/components/form/PointsForm/PointsForm.tsx
> +import { getCategories, getSubcategoriesByCategory } from "../../../api";
I believe after connecting points form with backend data all mock functions will be deleted to delete without causing troubles

2024-07-01 19:39 UTC, AnCichocka commented on frontend/src/hooks/Groups/useGroupsData.tsx
> +        fullName: userGroup.user.fullName ?? undefined,
I know, I wanted to left udefined - if fullName is empty there is no reason to display student card

2024-07-01 19:42 UTC, AnCichocka commented on frontend/src/screens/Groups/StudentSearcher/StudentCard.tsx
> +};
fair point

2024-07-01 19:46 UTC, AnCichocka commented on frontend/src/screens/Groups/StudentSearcher/StudentSearcher.tsx
> +
entirely agree

2024-07-01 19:48 UTC, AnCichocka commented on frontend/src/screens/Groups/Groups.tsx
> +    </div>
I think we will keep it on the same screen, that's how it is in our wireframes - to clarify during Figma war

2024-07-01 19:52 UTC, AnCichocka commented on frontend/src/hooks/Groups/useGroupsData.tsx
> +  const students: SearchStudent[] | undefined = data?.edition[0].groups.flatMap(
I guess it doesn't really make a difference - I used undefined, because It seemed to me simplier to contidion rendering. If you want me to change that I can, it doesn't make a difference to me

2024-07-01 19:58 UTC, dadamczykk commented on frontend/src/hooks/Groups/useGroupsData.tsx
> +  const students: SearchStudent[] | undefined = data?.edition[0].groups.flatMap(
that's alright, we can keep it

2024-07-01 20:09 UTC, AnCichocka commented on frontend/src/graphql/groupsByEdition.graphql
> +  }
I went for first approach I have one problem. Do you remember [my previous question](https://github.com/Jullija/oops/pull/23#discussion_r1661464400) With this query i need to use `bigint! `(otherwise it crashes on `yarn codegen`). What do we want to do in such case? I left   

```
const { data, loading, error } = useGroupsByEditionQuery({
    variables: {
      editionId: selectedEdition?.editionId as string,
    },
    skip: !selectedEdition,
  }); 
```

but it's clearly hacking types

2024-07-01 20:10 UTC, AnCichocka commented
I left some comments and did some changes. Thanks about a lot of useful information about graphql!

2024-07-01 20:21 UTC, dadamczykk commented on frontend/src/graphql/groupsByEdition.graphql
> +  }
ah yes, in this case lets write it with ```as string```. It won't affect anything and will make our type checks satisfied

2024-07-01 20:24 UTC, dadamczykk approved these changes
pięknie jest, można mergeować

2024-07-01 21:22 UTC, merged