Student profile rewriting, context updates
Jullija/oops pull request #24
Opened 2024-06-26 00:47 UTC by dadamczykk

2024-06-27 13:20 UTC, dadamczykk commented on frontend/src/components/Navbar.tsx
> +  };
This logic should be probably moved to separate hook, something like ```useSelectEdition```

2024-06-27 20:27 UTC, AnCichocka commented
I cannot select other edition:

https://github.com/Jullija/oops/assets/115690306/9d3ce00e-3303-4794-a2d5-5b4aa8df49c7

2024-06-27 20:41 UTC, Szyntos commented
> I cannot select other edition:
> 
>  Screen.Recording.2024-06-27.at.22.27.21.mov

i have the same issue, so reproduceable

2024-06-27 22:04 UTC, dadamczykk commented
> > I cannot select other edition:
> > Screen.Recording.2024-06-27.at.22.27.21.mov
> 
> i have the same issue, so reproduceable

this is probably because i've made changes to docker image of hasura, and the engine needs to be restarted after checkout to this branch

2024-06-27 23:27 UTC, dadamczykk commented
UPDATE

I've made changes so old points table is used with previous filters by category and points table. there may be new rows adding bonuses or date added but i'm not sure if it shouldn't be in some kind of modal

<img width="1162" alt="image" src="https://github.com/Jullija/oops/assets/70212130/2f93b38b-d96e-4ebe-8020-68b9ef14ffec">

2024-06-28 15:09 UTC, AnCichocka commented
> > > I cannot select other edition:
> > > Screen.Recording.2024-06-27.at.22.27.21.mov
> > 
> > 
> > i have the same issue, so reproduceable
> 
> this is probably because i've made changes to docker image of hasura, and the engine needs to be restarted after checkout to this branch

Now it work just fine!

2024-06-28 16:05 UTC, AnCichocka requested changes
Most of my comments are super trouper minor ones. Overall great piece of work and I really appreciate your fast changes which were made this night! I left some questions in the review :)

2024-06-28 16:11 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +        Total Points: {points.reduce((acc, point) => acc + +point.value, 0)}
So bigints from schema / db are converted to strings. We should use bigints only for Id, but there are still some bigint type fields in db that are no ids. One of them is ```point.value``` it gets queried as a string so i need to convert it to number

2024-06-28 16:14 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +  points: NonNullable<UserPointsQuery["usersByPk"]>["points"];
You mean to export a type ```Points``` that is type related to query?
Like:
```
export type Point = NonNullable<UserPointsQuery["usersByPk"]>["points"][number];
```

and than use it as you suggest?

I'd like to still use graphql generated types, but name simplification is a good idea. One drawback is that in the future we could have several queries that include points somewhere, and we would need to be cacious not to mess up types.

2024-06-28 16:17 UTC, Szyntos commented on frontend/src/components/userProfile/PointsTable.tsx
> +  const headers = ["Kategoria", "Podkategoria", "Punkty", "Prowadzący"];
maybe both (for foreign students / teachers)? idk how much work would it be, so just an idea

2024-06-28 16:18 UTC, dadamczykk commented on frontend/src/hooks/useStudentData.ts
> +  index: number;
I don't understand. ```UserCardProps``` have this ```index``` defined as ```number```

```
type UserCardProps = {
  fullName: string;
  index: number;
  points: NonNullable<UserPointsQuery["usersByPk"]>["points"];
};

export function UserCard({ fullName, index, points }: UserCardProps) {
```

also it is defined as a number from autogenerated ```UserPointsQuery```

```
export type UserPointsQuery = {
  __typename?: "query_root";
  usersByPk?: {
    __typename?: "Users";
    userId: string;
    firstName: string;
    indexNumber: number;
    nick: string;
    role: string;
    secondName: string;
    
    ```

2024-06-28 16:24 UTC, dadamczykk commented on frontend/src/screens/StudentProfile/StudentProfile.tsx
> +import { useStudentData } from "../../hooks/useStudentData";
This is correct import, I'm just not using ```index.ts``` in hooks folder. I think we should discuss approach, but personally i find putting index in every folder really boiler platey approach. It also could lead to some issues with circural imports, although it is rare.

2024-06-28 16:24 UTC, dadamczykk commented on frontend/src/screens/StudentProfile/StudentProfile.tsx
> +  if (!userData) return <p>Please select an edition.</p>;
Definetely we need to add some loader to our app, same for error message tile or something. I'll write tickets for that

2024-06-28 16:27 UTC, dadamczykk commented on frontend/src/components/userProfile/FilterMenu.tsx
> +>["points"][number]["subcategory"]["category"];
Category type that is retreived from ```UserPointsQuery```. ```NonNullable``` has to be added so I can refer to ```points```, because osmehow result of query is optional (idk why really, but it works)

2024-06-28 16:30 UTC, dadamczykk commented on frontend/src/hooks/useStudentData.ts
> +      error: error || null,
nothing really

2024-06-28 16:31 UTC, dadamczykk commented on frontend/src/hooks/useStudentData.ts
> +    fullName: `${firstName} ${secondName}`,
yes

2024-06-28 16:32 UTC, dadamczykk commented on frontend/src/components/userProfile/PointsTable.tsx
> +  const headers = ["Kategoria", "Podkategoria", "Punkty", "Prowadzący"];
Imo when it comes to FE polish. same should apply to backend names that are queried and displayed at fe. I'll make adjustements later

2024-06-28 16:33 UTC, dadamczykk commented on frontend/src/contexts/apolloClientContext.tsx
> +  uri: "http://127.0.0.1:9191/v1/graphql",
ofcourse we should. I'd love having env something, and perhaps we'll fix it than

2024-06-28 16:34 UTC, dadamczykk commented on frontend/src/utils/types.ts
> +export type Points = {
this is a mock type that should be delated in cleanup related pr

2024-06-28 16:41 UTC, Szyntos approved these changes

2024-06-28 18:51 UTC, AnCichocka commented on frontend/src/components/userProfile/userCard.tsx
> +        Total Points: {points.reduce((acc, point) => acc + +point.value, 0)}
I don't get it, so we want to have everything come to frontend as string except id?

2024-06-28 18:54 UTC, AnCichocka commented on frontend/src/components/userProfile/userCard.tsx
> +  points: NonNullable<UserPointsQuery["usersByPk"]>["points"];
I see both advantages and disadvantages, I like the idea of having simplified types like you showed above. If we decide on using those (I believe it's better idea) we need to remember not to export those types globally - messing up shouldn't be that much of a problem then

2024-06-28 18:55 UTC, AnCichocka commented on frontend/src/hooks/useStudentData.ts
> +  index: number;
I will check it again, but I am pretty sure I saw string `index` somewhere

2024-06-28 18:56 UTC, AnCichocka commented on frontend/src/screens/StudentProfile/StudentProfile.tsx
> +import { useStudentData } from "../../hooks/useStudentData";
Ok, I am open to a discussion about that! (I'm not really sure what is the "correct" approach to index.ts)

2024-06-28 18:56 UTC, AnCichocka commented on frontend/src/components/userProfile/FilterMenu.tsx
> +>["points"][number]["subcategory"]["category"];
Looks crazy

2024-06-28 19:18 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +        Total Points: {points.reduce((acc, point) => acc + +point.value, 0)}
no, quite the opposite. FE gets id as a string, the rest has its db types (strings, numbers basically) this one comes to fe as a string because of error on backend site.

2024-06-28 19:21 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +        Total Points: {points.reduce((acc, point) => acc + +point.value, 0)}
The bigints on BE should come to FE as strings, and they do. The thing is Bigints should be used only for ID's, normal numbers should be int or float (and they would come to fe as numeric values). But there are still some mismatch in backend db schema, thats why for now we have to handle value like that (because it is defined as a bigint instead of float, and comes to fe as string)

2024-06-28 19:23 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +  points: NonNullable<UserPointsQuery["usersByPk"]>["points"];
It will be alright to export them if we keep the naming right or we check imports. For example in this case this type is reused several times, so no exporting it and defining in every component seems not right

2024-06-28 20:25 UTC, dadamczykk commented on frontend/src/components/userProfile/userCard.tsx
> +      </p>
good idea, i'll replace it as a divs, than we should probably create class typography for text entries

2024-06-28 20:58 UTC, dadamczykk commented on frontend/src/contexts/apolloClientContext.tsx
> +  uri: "http://127.0.0.1:9191/v1/graphql",
Ideally it's going to by an env variable based on enviroment (it could be either local or dev) but yes, for now it should be const

2024-06-28 21:28 UTC, dadamczykk commented on frontend/src/screens/Welcome.tsx
> +          <tbody>
It doesn't really matter, whole welcome screen is temporary till we do not have well done login

2024-06-28 22:36 UTC, AnCichocka commented on frontend/src/screens/Welcome.tsx
> +          <tbody>
I was just joking... I know

2024-06-29 11:31 UTC, AnCichocka approved these changes
Thanks, looks good! I added only super ultra minor suggestions 🥇

2024-06-29 11:31 UTC, AnCichocka commented on frontend/src/components/Navbar.tsx
> +      {showEditionSelection && (
just a heads up, if user has no editions, he/she will see multiple selection

2024-06-29 11:31 UTC, AnCichocka commented on frontend/src/components/userProfile/userCard.tsx
> +// those styles will be changed, i've just chat-gptd them
add TODO please - it will help us later on

2024-06-29 11:31 UTC, AnCichocka commented on frontend/src/graphql/userPoints.graphql.types.ts
> +        fullName?: string | null;
is `null` necessary here?
```suggestion
        fullName?: string;
```

2024-06-29 11:31 UTC, AnCichocka commented on frontend/src/hooks/useStudentData.ts
> +  index: number;
I checked it, I was wrong, sorry

2024-06-29 11:31 UTC, AnCichocka commented on frontend/src/screens/Welcome.tsx
> +// again - chat gptd styles, also do not bother about this component, it is temporary till login isn't implemented
add TODO please

2024-06-29 11:35 UTC, dadamczykk commented on frontend/src/graphql/userPoints.graphql.types.ts
> +        fullName?: string | null;
It's auto generated, so I wouldn't change that

2024-06-29 11:37 UTC, dadamczykk commented on frontend/src/components/Navbar.tsx
> +      {showEditionSelection && (
Not exactly because of how it is defined.```  const showEditionSelection = editions.length > 1;``` If user has no editions it will fall in first div, but without content (because name is undefined in that case). You can see it on welcome page when no user is selected.

2024-06-29 11:40 UTC, merged