Query images from backend
Jullija/oops pull request #28
Opened 2024-07-02 20:36 UTC by dadamczykk

https://www.loom.com/share/150a411c748e4fb5a19b29d576d199a3?sid=dd9f8d4e-7274-48ad-846e-5d3b12e32669

2024-07-04 18:25 UTC, AnCichocka commented
(no one cares about css properties for now)

2024-07-04 18:42 UTC, AnCichocka requested changes
Please check if useUserPointsImage detects the smallest level. I also left some comments here: https://github.com/Jullija/oops/commit/6b4198c0c2d3511bf84120d92b339fb1a8739e07. Overall, looks good!

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/components/StudentProfile/userCard.tsx
> +        {imageId && !loading && !error ? (
```suggestion
        {displayImage ? (
```
please

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/components/StudentProfile/userCard.tsx
> +          !loading && !error && <div style={styles.userImageContainer} />
I would like it to be exported to variable and named properly like `showImageAltComponent`

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/components/hallOfFame/hallOfFameHeader.tsx
> +    zIndex: 9,
Scary (joking)

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/hooks/useUserPointsImage.ts
>        ) {
see my comment - https://github.com/Jullija/oops/commit/6b4198c0c2d3511bf84120d92b339fb1a8739e07#r143854769

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/hooks/useUserPointsImage.ts
> +        (level.maximumPoints ? points < +level.maximumPoints : true)
Just thinking if it's not more readable, but without difference to me

```suggestion
        && (!level.maximumPoints || points < +level.maximumPoints)
```

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/hooks/useUserPointsImage.ts
>        return false;
I believe you don't cover variant with first level?

2024-07-04 18:42 UTC, AnCichocka commented on frontend/src/hooks/useUserPointsImage.ts
>        return false;
I'm not sure what `highest` in `level.highest` means, but if it's the highest level of all levels no objections

2024-07-28 20:51 UTC, Szyntos commented on frontend/src/hooks/useUserPointsImage.ts
> +    // TODO logic to find out which level is user
this is in a PR, so i didn't bother checking

2024-08-14 18:04 UTC, AnCichocka approved these changes
Hall of fame may look off after this merge, but don't worry, some files are deleted anyway in other PRs

2024-08-14 18:04 UTC, merged