[99] Added getGroupsInEdition
Jullija/oops pull request #88
Opened 2024-09-07 20:04 UTC by Szyntos

```graphql
query MyQuery {
  getGroupsInEdition(editionId: 3, teacherId: 1) {
    canEdit
    owns
    group {
      groupsId
    }
  }
}
```

2024-09-07 20:13 UTC, Jullija requested changes

2024-09-07 20:13 UTC, Jullija commented on backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
> +        if (teacher.role != UsersRoles.TEACHER && teacher.role != UsersRoles.COORDINATOR) {
It's better to do

 ` if (teacher.role == UserRoles.STUDENT) `

2024-09-07 20:26 UTC, Szyntos commented on backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
> +        if (teacher.role != UsersRoles.TEACHER && teacher.role != UsersRoles.COORDINATOR) {
Imo clearer is to state that you're trying to query for a user that is NOT a teacher NOR a coordinator

and it's futureproof, what if we would add a userRole 'unauthenticated'

2024-09-08 10:05 UTC, Jullija approved these changes

2024-09-08 10:09 UTC, merged