Add points
Jullija/oops pull request #96
Opened 2024-09-11 15:01 UTC by AnCichocka

2024-09-26 20:04 UTC, AnCichocka commented
@Szyntos I would like you to test this out - I faced some backend errors

2024-09-28 21:55 UTC, Szyntos requested changes
Small change, but overall big brain PR

2024-09-28 21:55 UTC, Szyntos commented on frontend/src/graphql/formCategories.graphql
> +query FormCategories($editionId: bigint!) {
```graphql
query FormCategories {
  categories(orderBy: {categoryName: ASC}, where: {categoryEditions: {editionId: {_eq: 1}}}) {
    categoryId
    categoryName
    subcategories(orderBy: {ordinalNumber: ASC}, where: {editionId: {_eq: 1}}) {
      subcategoryId
    }
    canAddPoints
  }
}
```


You should also check the category's edition

2024-09-28 21:55 UTC, Szyntos commented on frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx
> +            variant="edit"
imo the text on all of the buttons should be "Confirm"

2024-09-28 22:23 UTC, AnCichocka commented on frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx
> +            variant="edit"
I don't think so, I believe CTA button should describe what it does - add or edit, but we can discuss it further

2024-09-28 22:26 UTC, AnCichocka commented on frontend/src/graphql/formCategories.graphql
> +query FormCategories($editionId: bigint!) {
done

2024-09-29 00:59 UTC, Szyntos approved these changes

2024-09-29 08:48 UTC, merged